bitextor: /home/hieu/workspace/github/paracrawl/bitextor.malign
hosts: ["www.elenacaffe1863.com","vade-retro.fr"]
#hosts: ["www.icgeb.org", "aletheia.ro", "ams.impa.br"]
#hostPath: /home/hieu/permanent/data/hosts/hosts.fr.3.gz
#excludeHosts: ["vade-retro.fr"]

  #"langstat: /home/hieu/permanent/software/langstat/1k.gz
  #"langstatThreshold":10,

  #"langstat: /home/hieu/permanent/software/langstat/langstats.all.gz
  #"langstatThreshold":50000000,
#linkedHosts: ["/home/hieu/permanent/other-en"]
#linkedHostsAction: link

langstatExcludeStrings: /home/s0565741/workspace/github/paracrawl/bitextor.malign/snakemake/langstat-exclude-strings
excludeHostsFile: /home/s0565741/workspace/github/paracrawl/bitextor.malign/snakemake/exclude-hosts
crawlerUserAgent: Mozilla/5.0 (compatible; Paracrawl; +http://statmt.org/paracrawl/robots.html)
httrack: true

temp: /tmp
permanentDir: /home/hieu/workspace/experiment/issues/paracrawl/workspace/fr-en.tiny/permanent
transientDir: /home/hieu/workspace/experiment/issues/paracrawl/workspace/fr-en.tiny/transient
lang1: fr
lang2: en
crawlTimeLimit: 60s
crawlPageLimit: 100000
crawlerNumThreads: 2
crawlTld: false

deduped: true
tmx: true
storeRawCorpus: true
elrc: true
documentAligner: externalMT
alignerCmd: "/home/hieu/workspace/experiment/issues/paracrawl/phi-system/translate-pipe.sh fr"
bleualign: true
docAlignThreshold: 0.1
bleuAlignThreshold: 0.2
maxSizeWARC: 5000

